version: '3'
services:
  agent:
    image: "nginx:alpine"
    volumes:
        - ./:/var/www
        - ./nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "9090:80"
    environment:
      NODE_ENV: production
    restart: unless-stopped
